### ISSUE TITLE
InvalidJsonException is thrown when the property is not exist.

### ISSUE THREAD

**Issue by poemn** [alps-asd/app-state-diagram#151]
### Bug Report

InvalidJsonException is thrown when the property is not defined.  

This problem occur only in JSON.

### How to reproduce

```json
    "descriptor": [
      {
        "id": "id",
        "aaaa": "hogehoge"
      }
    ]
```

**Comment by koriym** [comment]
It has no problem ignoring tags it doesn't know. It is a specification.

**Comment by koriym** [comment]
However, it might be a good idea to put it out in a log?
