### ISSUE TITLE
Dump Workflow ASD

### ISSUE THREAD

**Issue by NaokiTsuchiya** [alps-asd/app-state-diagram#169]
# 概要

既に複数のタグによるextractの機能は実装されていますが、都度ASDを実行する必要があります。加えて、indexからのリンクもなく、ホスティングするにはむいていません。

https://github.com/alps-asd/app-state-diagram/issues/139 にて、optionを廃止して常にdumpされるようになりました。

上記のように、複数のタグの組み合わせに対してlabelを付与し、常にdumpされるようにします。

# 変更内容

### Current

```xml
<asd>
  <filter>
    <and>foo</and>
  </filter>
</asd>
```

### Proporsal

Add `workflow` element.

※ Consider cases where configurations are not used. (ex. ALPS tag of `workflow:{workflowName}`

```xml
<asd>
  <workflow>
    <filter name="createBlogPost">
      <and>foo</and>
    </filter>
   <filter name="readBlogPost">
      <and>bar</and>
    </filter>
  </workflow>
</asd>
```

### current

<img width="894" alt="image" src="https://user-images.githubusercontent.com/17171732/190546202-a2310434-d918-4d54-aa86-6db847d5be58.png">

### Proporsal

Add `Workflows` to ASD index page

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/17171732/190546174-dc18b2bf-0092-467b-9dd9-fb4ddd0d5d36.png">

**Comment by koriym** [comment]
動的にSVG表示を変更するようにしたのでこのissueは閉じます！
