### ISSUE TITLE
ツールチップにHTMLタグが入る場合がある

### ISSUE THREAD

**Issue by apple-x-co** [alps-asd/app-state-diagram#171]
### Bug Report

ツールチップにHTMLタグが入っている

<img width="579" alt="スクリーンショット 2022-09-21 13 54 42" src="https://user-images.githubusercontent.com/8497012/191417480-2886b368-b448-41fb-b162-bfc80c17f88f.png">

<img width="749" alt="スクリーンショット 2022-09-21 13 54 50" src="https://user-images.githubusercontent.com/8497012/191417494-af4ea125-87f2-4d63-9c63-baba1ad29a75.png">

### How to reproduce

1. `type=unsafe` の descriptor を用意
2. `--label=both` を有効にしてASDを実行

**Comment by koriym** [comment]
TodoMVCで`<TABLE>`と表示されます。

https://alps-asd.github.io/app-state-diagram/todomvc/docs/asd.html

<img width="501" alt="image" src="https://user-images.githubusercontent.com/529021/202655007-2d53609c-0de9-4860-8b20-99d162824c96.png">

SVGのソースを見ると

```
<title>TodoItem</title>
<g id="a_node1"><a xlink:href="docs/semantic.TodoItem.html" xlink:title="&lt;TABLE&gt;" target="_parent">
```

この`xlink:title`が問題だと思われます。

**Comment by koriym** [comment]
@apple-x-co リリースしました！
https://github.com/alps-asd/app-state-diagram/releases/tag/0.10.2

複数のラベルがある時にtableタグを使っててそれがそのままタイトトルになり評価されてたようです。`tooltip`という要素を設定して解決しました。
