### ISSUE TITLE
2つのALPSファイルを同時にローカルプレビューしたい

### ISSUE THREAD

**Issue by shellme** [alps-asd/app-state-diagram#176]
`asd --watch` コマンドで1つのファイルをプレビューしている最中に、別のファイルも `asd --watch` で動かして見比べたいときがあります。

試してみたところポート番号が同じになり実行ができなかったのですが、ポート番号を別で指定するなど方法はあるでしょうか？

**Comment by NaokiTsuchiya** [comment]
`bin/asd` 実行時に `--port` オプションを指定することで任意のportで起動できるようにします。
